name: Deploy Backend

on:
  push:
    branches:
    - master # Only trigger on the development branch

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run:  apk add ruby && gem install mustache
      - name: creates output
        run:  sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: output/
          destination-github-username: 'cpina'
          destination-repository-name: 'MusicRemixer'
          user-email: sudipmondal.2002@rediffmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: backend
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
