name: Deploy Site

on:
  push:
    branches:
    - master # Only trigger on the development branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./backend
        publish_branch: backend
