name: Build & deploy

on:
  push:
    branches:
      - web

jobs:
  deploy:
    name: deploy to staging
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy React code to GitHub Pages
        uses: amitsingh-007/deploy-to-github-pages@v1.2
