name: Build & deploy

on:
  push:
    branches:
      - web

jobs:
  deploy:
    name: deploy to staging
    runs-on: ubuntu-latest
    
    steps:
      - name: branch web
        run: git checkout web
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
